"""
帰納法ステップの代数的検証 (sympy不要版)
"""
from fractions import Fraction

print("=== 帰納法ステップの代数的検証 ===")
print()
print("帰納法ステップ:")
print("  S_{K+1} = S_K + f(K)")
print("  where S_K = 2 - (K+2)/2^K")
print("  and f(K) = (K+1)/2^{K+1}")
print()
print("検証: [2-(K+2)/2^K] + (K+1)/2^{K+1} = 2-(K+3)/2^{K+1}")
print()
print("共通分母 2^{K+1} で統一:")
print("  -(K+2)/2^K = -2(K+2)/2^{K+1}")
print("  LHS のマイナス部分: [-2(K+2) + (K+1)] / 2^{K+1}")
print("  = [-2K-4+K+1] / 2^{K+1}")
print("  = -(K+3) / 2^{K+1}")
print("  = RHS のマイナス部分 ✓")
print()

print("=== 数値検証 ===")
for K in range(0, 15):
    lhs = Fraction(2) - Fraction(K+2, 2**K) + Fraction(K+1, 2**(K+1))
    rhs = Fraction(2) - Fraction(K+3, 2**(K+1))
    match = "✓" if lhs == rhs else "✗"
    print(f"K={K:2d}: LHS={float(lhs):.10f}, RHS={float(rhs):.10f} {match}")

print()
print("=== field_simp + ring が動く理由 ===")
print("field_simp: 全ての分母 2^K, 2^{K+1} を消去 (pow_ne_zero で ≠ 0)")
print("ring: 残った多項式等式を決定手続きで処理")
print()
print("注: Lean の sum_range_succ 適用後の goal は")
print("  2 - (↑K + 2) / 2^K + (↑K + 1 + 1) / 2^(K + 1 + 1) = 2 - (↑K + 1 + 2) / 2^(K+1)")
print("  = 2 - (↑K + 2) / 2^K + (↑K + 2) / 2^(K+2) = 2 - (↑K + 3) / 2^(K+1)")
print()
print("Wait - f(K) は j = K のときの項:")
print("  f(K) = (K + 1) / 2^{K+1}")
print("  (Lean: (↑K + 1 : ℝ) / 2 ^ (K + 1))")
print("  ※ sum_range_succ は最後の項 f(K) を足す")

print()
print("=== Lean での sum_range_succ 後の正確な goal ===")
print("ih: ∑ j in range K, ((↑j + 1) / 2^(j+1)) = 2 - (↑K + 2) / 2^K")
print("goal: ∑ j in range (K+1), ((↑j + 1) / 2^(j+1)) = 2 - (↑(K+1) + 2) / 2^(K+1)")
print()
print("sum_range_succ 適用後:")
print("  (∑ j in range K, ((↑j + 1) / 2^(j+1))) + ((↑K + 1) / 2^(K+1))")
print("  = 2 - (↑K + 1 + 2) / 2^(K+1)")
print()
print("ih で書き換え後:")
print("  (2 - (↑K + 2) / 2^K) + ((↑K + 1) / 2^(K+1))")
print("  = 2 - (↑K + 3) / 2^(K+1)")
print()
print("field_simp で分母消去, ring で確認:")
print("  LHS * 2^{K+1}: 2 * 2^{K+1} - (K+2) * 2 + (K+1) = 2^{K+2} - K - 3")
print("  RHS * 2^{K+1}: 2 * 2^{K+1} - (K+3) = 2^{K+2} - K - 3 ✓")

print()
print("=== tendsto_remainder の分解戦略 ===")
print("(↑K + 2) / 2^K = ↑K * (1/2)^K + 2 * (1/2)^K")
print()
for K in range(0, 10):
    lhs_val = Fraction(K+2, 2**K)
    rhs_val = Fraction(K, 2**K) + Fraction(2, 2**K)
    match = "✓" if lhs_val == rhs_val else "✗"
    print(f"K={K:2d}: (K+2)/2^K = {float(lhs_val):.6f}, K*(1/2)^K + 2*(1/2)^K = {float(rhs_val):.6f} {match}")

print()
print("Mathlib API:")
print("  tendsto_self_mul_const_pow_of_lt_one (0 ≤ 1/2) (1/2 < 1):")
print("    Tendsto (fun n => ↑n * (1/2)^n) atTop (nhds 0)")
print("  tendsto_pow_atTop_nhds_zero_of_lt_one (0 ≤ 1/2) (1/2 < 1):")
print("    Tendsto (fun n => (1/2)^n) atTop (nhds 0)")
print("  .const_mul 2:")
print("    Tendsto (fun n => 2 * (1/2)^n) atTop (nhds (2*0)) = nhds 0")
print("  .add: 二つの Tendsto の和 → nhds (0+0) = nhds 0")

