"""
Exploration Part 3: Key structural discoveries

Focus on:
1. Semigroup size pattern: 2, 12, 60 = 2, 2*6, 2*6*5 ??
2. The remarkable pattern in all-1 v2 sequence: B = 3^k - 1
3. The connection between constant maps and reachable residues
4. Algebraic structure of 2^{-j} orbit in (Z/3^K Z)*
"""

import json
from collections import defaultdict
from itertools import product
from math import gcd

def syracuse(n):
    if n % 2 == 0:
        raise ValueError(f"n must be odd, got {n}")
    x = 3 * n + 1
    v = 0
    while x % 2 == 0:
        x //= 2
        v += 1
    return x, v

def syracuse_iter(n, k):
    v2_seq = []
    current = n
    for _ in range(k):
        current, v = syracuse(current)
        v2_seq.append(v)
    return current, v2_seq

def compute_Tk_mod3k(v2_seq):
    k = len(v2_seq)
    if k == 0:
        return None
    mod = 3**k
    S = [0]
    for j in v2_seq:
        S.append(S[-1] + j)
    Ck = 0
    for i in range(k):
        Ck = (Ck + pow(3, k-1-i, mod) * pow(2, S[i], mod)) % mod
    Sk = sum(v2_seq)
    inv_2Sk = pow(2, -Sk, mod)
    return (Ck * inv_2Sk) % mod

# ============================================================
# 1. Semigroup size pattern
# ============================================================

print("=" * 70)
print("1. Semigroup size analysis")
print("=" * 70)

for K in range(1, 7):
    mod = 3**K

    def compose(f, g):
        """g o f: first apply f, then g."""
        return tuple(g[f[r]] for r in range(mod))

    # Generate f_j for j=1,...,2*3^{K-1} (one full period)
    ord_val = 2 * 3**(K-1)
    generators = {}
    for j in range(1, ord_val + 1):
        inv2j = pow(2, -j, mod)
        fj = tuple((3 * inv2j * r + inv2j) % mod for r in range(mod))
        generators[j] = fj

    # Distinct generators
    distinct_gens = set(generators.values())

    # Generate semigroup
    semigroup = set(distinct_gens)
    frontier = set(distinct_gens)

    for depth in range(1, 20):
        new_elements = set()
        for func in list(frontier):
            for gen in distinct_gens:
                composed = compose(func, gen)
                if composed not in semigroup:
                    new_elements.add(composed)
                    semigroup.add(composed)
        frontier = new_elements
        if not frontier:
            break

    # Analysis
    constant_funcs = [f for f in semigroup if all(f[r] == f[0] for r in range(mod))]
    constant_values = {f[0] for f in constant_funcs}

    print(f"\nK={K}, mod={mod}:")
    print(f"  ord_{{3^K}}(2) = {ord_val}")
    print(f"  Distinct generators: {len(distinct_gens)}")
    print(f"  Semigroup size: {len(semigroup)}")
    print(f"  Constant functions: {len(constant_funcs)}")
    print(f"  Constant values = coprime residues: {len(constant_values)}")
    print(f"  phi(3^K) = {2 * 3**(K-1)}")
    print(f"  Semigroup / phi(3^K) = {len(semigroup) / (2 * 3**(K-1)):.1f}")

    # Idempotent structure
    idempotents = [f for f in semigroup if compose(f, f) == f]
    print(f"  Idempotents: {len(idempotents)}")

    if K <= 4:
        # Check: is the semigroup generated by just f_1 and f_2?
        gens_12 = {generators[1], generators[2]}
        sg_12 = set(gens_12)
        fr_12 = set(gens_12)
        for depth in range(1, 30):
            new_12 = set()
            for func in list(fr_12):
                for gen in gens_12:
                    c = compose(func, gen)
                    if c not in sg_12:
                        new_12.add(c)
                        sg_12.add(c)
            fr_12 = new_12
            if not fr_12:
                break
        print(f"  Semigroup from {{f_1, f_2}} only: {len(sg_12)}")
        print(f"  Same as full semigroup: {sg_12 == semigroup}")

# ============================================================
# 2. Pattern in intercepts for constant v2 sequences
# ============================================================

print("\n" + "=" * 70)
print("2. Patterns in constant v2 sequences")
print("=" * 70)

# For v2 = (j, j, ..., j) (all same), what is R_k?
for j in range(1, 6):
    print(f"\nv2 = ({j}, {j}, ..., {j}):")
    for k in range(1, 8):
        v2_seq = [j] * k
        val = compute_Tk_mod3k(v2_seq)
        mod = 3**k
        # Also compute 2^{-j} / (1 - 3*2^{-j}) mod 3^k
        # From geometric series: R = 2^{-j} * sum_{i=0}^{k-1} (3*2^{-j})^i
        # = 2^{-j} * (1 - (3*2^{-j})^k) / (1 - 3*2^{-j})
        inv2j = pow(2, -j, mod)
        term = (3 * inv2j) % mod
        geo_sum = sum(pow(term, i, mod) for i in range(k)) % mod
        formula_val = (inv2j * geo_sum) % mod

        # Check: is this 1/(2^j - 3) mod 3^k?
        if pow(2, j, mod) != 3 % mod:
            inv_2j_minus_3 = pow(pow(2, j, mod) - 3, -1, mod) if gcd(pow(2, j, mod) - 3, mod) == 1 else "N/A"
        else:
            inv_2j_minus_3 = "N/A"

        print(f"  k={k}: R_k = {val}, formula = {formula_val}, "
              f"1/(2^{j}-3) mod 3^{k} = {inv_2j_minus_3}")

# ============================================================
# 3. Beautiful pattern: j=1 all-ones gives 3^k - 1
# ============================================================

print("\n" + "=" * 70)
print("3. Special case: all v2=1")
print("=" * 70)

print("\nv2 = (1,1,...,1) of length k:")
for k in range(1, 10):
    v2_seq = [1] * k
    val = compute_Tk_mod3k(v2_seq)
    mod = 3**k
    print(f"  k={k}: T^k(n) mod 3^k = {val} = 3^{k} - {mod - val}")

# This should be 3^k - 1 = 1/(2-3) = -1 in Z_3
# Verified: -1 mod 3^k = 3^k - 1

print("\nInterpretation: v2 = (1,1,...,1) => T^k(n) = -1 (mod 3^k)")
print("This means T^k(n) ≡ -1 in Z_3 for the all-1 trajectory")
print("-1 in Z_3 = ...222 (all digits = 2)")

# Check: what about all-2?
print("\nv2 = (2,2,...,2) of length k:")
for k in range(1, 10):
    v2_seq = [2] * k
    val = compute_Tk_mod3k(v2_seq)
    mod = 3**k
    # 1/(4-3) = 1 mod 3^k = 1
    print(f"  k={k}: T^k(n) mod 3^k = {val}")

print("\nv2 = (2,2,...,2) => T^k(n) ≡ 1 (mod 3^k)")
print("This means T^k(n) = 1 in Z_3 for the all-2 trajectory")
print("1 in Z_3 = ...001 (d_1=1, rest=0)")

# What about j=3?
print("\nv2 = (3,3,...,3) of length k:")
for k in range(1, 10):
    v2_seq = [3] * k
    val = compute_Tk_mod3k(v2_seq)
    mod = 3**k
    # 1/(8-3) = 1/5 mod 3^k
    inv5 = pow(5, -1, mod) if gcd(5, mod) == 1 else "N/A"
    print(f"  k={k}: T^k(n) mod 3^k = {val}, 1/5 mod 3^k = {inv5}")

print("\nv2 = (j,j,...,j) => T^k(n) -> 1/(2^j - 3) in Z_3")

# ============================================================
# 4. The 3-adic limit as a function of the v2 sequence
# ============================================================

print("\n" + "=" * 70)
print("4. 3-adic limit for various periodic v2 sequences")
print("=" * 70)

# If v2 = (a, b, a, b, ...) periodic with period 2
# Then f_b o f_a is iterated. The fixed point gives the 3-adic limit.
# f_b(f_a(R)) = (3*2^{-b})(3*2^{-a}*R + 2^{-a}) + 2^{-b}
# = 9*2^{-(a+b)}*R + 3*2^{-(a+b)} + 2^{-b}
# Fixed point: R = (3*2^{-(a+b)} + 2^{-b}) / (1 - 9*2^{-(a+b)})
# = (3 + 2^a) / (2^{a+b} - 9)

for a in range(1, 5):
    for b in range(1, 5):
        if 2**(a+b) == 9:
            print(f"  (a,b)=({a},{b}): 2^(a+b) = 9, singular!")
            continue
        denom = 2**(a+b) - 9
        numer = 3 + 2**a
        if denom == 0:
            continue
        # Compute in 3-adic (mod 3^8)
        K = 8
        mod = 3**K
        if gcd(denom, mod) != 1:
            continue
        limit_val = (numer * pow(denom, -1, mod)) % mod

        # Verify with transducer
        v2_seq = [a, b] * K
        val = compute_Tk_mod3k(v2_seq[:K])

        digits = []
        v = limit_val
        for _ in range(K):
            digits.append(v % 3)
            v //= 3

        print(f"  period=(a={a},b={b}): limit = {numer}/{denom} = {limit_val} mod 3^{K}, "
              f"digits = {digits[:6]}...")
        print(f"    transducer (k={K}): {val}")

# ============================================================
# 5. Algebraic structure: connection to 2-adic/3-adic duality
# ============================================================

print("\n" + "=" * 70)
print("5. The transducer as a 2-adic to 3-adic converter")
print("=" * 70)

# The v2 sequence (j_1, j_2, ...) encodes the 2-adic structure of the orbit.
# Specifically, j_k = v_2(3*T^{k-1}(n) + 1).
# The sequence of partial sums S_k = j_1+...+j_k controls the 2-adic shrinkage.
#
# The transducer converts this 2-adic information into 3-adic information:
# T^k(n) mod 3^k (determined by v2 sequence alone).
#
# Key duality:
# - 2-adic side: n mod 2^m determines what happens to the TRAJECTORY
# - 3-adic side: v2 sequence determines what T^k(n) looks like mod 3^k

# The "forward" map: v2 sequence -> 3-adic expansion of the limit
# The "inverse" question: can we go from 3-adic to 2-adic?

# Check: given T^k(n) mod 3^k, what can we infer about the v2 sequence?
print("\nInverse problem: can we recover v2 from 3-adic data?")

# For K=2, the 6 coprime residues mod 9 correspond to:
mod9 = 9
for r in [1, 2, 4, 5, 7, 8]:
    # Which (j1, j2) pairs give this residue?
    pairs = []
    for j1 in range(1, 13):
        for j2 in range(1, 13):
            val = compute_Tk_mod3k([j1, j2])
            if val == r:
                pairs.append((j1, j2))
    # Reduce mod 6
    reduced = set((j1 % 6 if j1 % 6 > 0 else 6, j2 % 6 if j2 % 6 > 0 else 6) for j1, j2 in pairs)
    print(f"  R={r} (d1={r%3}, d2={r//3}): {len(reduced)} reduced (j1%6, j2%6) pairs")
    if len(reduced) <= 8:
        print(f"    pairs: {sorted(reduced)}")

# ============================================================
# 6. Semigroup structure deeper analysis
# ============================================================

print("\n" + "=" * 70)
print("6. Semigroup factorization pattern")
print("=" * 70)

# Sizes: K=1: 2, K=2: 12, K=3: 60
# Ratios: 12/2 = 6, 60/12 = 5
# Let's compute more

semigroup_sizes = {}
for K in range(1, 6):
    mod = 3**K
    ord_val = 2 * 3**(K-1)

    distinct_gens = set()
    for j in range(1, ord_val + 1):
        inv2j = pow(2, -j, mod)
        fj = tuple((3 * inv2j * r + inv2j) % mod for r in range(mod))
        distinct_gens.add(fj)

    semigroup = set(distinct_gens)
    frontier = set(distinct_gens)
    for depth in range(1, 30):
        new_elements = set()
        for func in list(frontier):
            for gen in distinct_gens:
                composed = tuple(gen[func[r]] for r in range(mod))
                if composed not in semigroup:
                    new_elements.add(composed)
                    semigroup.add(composed)
        frontier = new_elements
        if not frontier:
            print(f"  K={K}: semigroup stabilized at depth {depth}")
            break

    semigroup_sizes[K] = len(semigroup)

print("\nSemigroup sizes:")
for K, size in semigroup_sizes.items():
    phi = 2 * 3**(K-1)
    print(f"  K={K}: |S| = {size}, phi(3^K) = {phi}, |S|/phi = {size/phi:.1f}")

# Check ratios
sizes = [semigroup_sizes[K] for K in sorted(semigroup_sizes.keys())]
print("\nRatios |S_{K+1}| / |S_K|:")
for i in range(len(sizes) - 1):
    print(f"  K={i+1} -> K={i+2}: {sizes[i+1]}/{sizes[i]} = {sizes[i+1]/sizes[i]:.4f}")

# ============================================================
# 7. Connection to the orbits of 2 in (Z/3^K Z)*
# ============================================================

print("\n" + "=" * 70)
print("7. Orbit of 2 and transducer generators")
print("=" * 70)

for K in range(1, 5):
    mod = 3**K
    ord_val = 2 * 3**(K-1)

    # The generators f_j for j=1,...,ord_val
    # f_j(R) = (3R+1)*2^{-j} mod 3^K
    # The generator is determined by 2^{-j} mod 3^K
    # which runs through ALL elements of <2> = (Z/3^K Z)* as j=1,...,ord_val

    gen_set = set()
    for j in range(1, ord_val + 1):
        inv2j = pow(2, -j, mod)
        gen_set.add(inv2j)

    coprime_set = {r for r in range(mod) if gcd(r, mod) == 1}

    print(f"\nK={K}: {len(gen_set)} distinct 2^{{-j}} values = (Z/3^KZ)* of size {len(coprime_set)}")
    print(f"  Covers all coprime residues: {gen_set == coprime_set}")

    # So the set of generators {f_1,...,f_{ord}} parameterizes ALL
    # elements of the group (Z/3^K Z)*

    # The affine map f_j(R) = c*(3R+1) where c = 2^{-j} runs over (Z/3^K Z)*
    # These are ALL possible affine maps of the form c*(3R+1) where c is a unit.
    # Equivalently: f_c(R) = 3cR + c for c in (Z/3^K Z)*

    # The semigroup is generated by {f_c : c in U_K} where U_K = (Z/3^K Z)*
    # f_c(R) = 3cR + c = c(3R + 1)

    # Composition: f_c o f_d(R) = f_c(3dR + d) = 3c(3dR + d) + c
    # = 9cdR + 3cd + c
    # = 3(3cd)R + (3cd + c)

    # This is NOT of the form f_e(R) = 3eR + e unless 3cd + c = 3cd + c... wait
    # f_e(R) = 3eR + e, so we need: 9cd = 3e and 3cd + c = e
    # From second: e = 3cd + c = c(3d+1)
    # From first: 3e = 9cd => e = 3cd
    # So need c(3d+1) = 3cd => c = 0, contradiction.
    # So the semigroup is NOT just {f_c : c in U}!

    # The general element after two compositions is:
    # g(R) = 9cdR + (3cd + c) = 3*(3cd)*R + (3cd + c)
    # slope = 9cd, intercept = 3cd + c = c(3d+1)

    # After k compositions: slope = 3^k * prod(c_i), intercept = complicated
    # The slope is always divisible by 3^k.
    # After k >= K steps, slope = 0 mod 3^K => constant function.

    # So the semigroup consists of:
    # - Level 1: maps of form 3cR + c (slope = 3c, c in U_K)
    # - Level 2: maps of form 9cdR + c(3d+1) (slope = 9cd)
    # - ...
    # - Level K: constant maps (slope = 0)

    # Count elements at each level
    level_funcs = defaultdict(set)
    for func in [(tuple((3 * pow(2, -j, mod) * r + pow(2, -j, mod)) % mod
                         for r in range(mod)), j)
                 for j in range(1, ord_val + 1)]:
        level_funcs[1].add(func[0])

    # Generate level by level
    all_funcs = set()
    current_level = level_funcs[1]
    all_funcs.update(current_level)

    for level in range(2, K + 2):
        next_level = set()
        for func in current_level:
            for gen in level_funcs[1]:
                composed = tuple(gen[func[r]] for r in range(mod))
                if composed not in all_funcs:
                    next_level.add(composed)
                    all_funcs.add(composed)
        level_funcs[level] = next_level
        current_level = next_level

    print(f"  Level-by-level generation:")
    total = 0
    for level in sorted(level_funcs.keys()):
        size = len(level_funcs[level])
        total += size
        # Check if all funcs at this level have same slope behavior
        slopes = set()
        for func in level_funcs[level]:
            # Slope = func[1] - func[0] mod 3^K... not quite
            # For affine f(R) = aR + b, slope = f(1)-f(0)
            slope = (func[1] - func[0]) % mod
            slopes.add(slope)
        v3_slopes = set()
        for s in slopes:
            v = 0
            ss = s
            while ss > 0 and ss % 3 == 0:
                ss //= 3
                v += 1
            if s == 0:
                v = K
            v3_slopes.add(v)
        print(f"    Level {level}: {size} functions, v3(slope) values: {sorted(v3_slopes)}")
    print(f"    Total: {total}")

print("\n\nDone!")
